// front/src/routes/login/+page.svelte
<script>
    import { login } from "../../services/auth.js";

    let haveError = false;

    let username = "";
    let password = "";
    let rememberMe = true;

    function onLogin() {
        haveError = false;
        login(username, password, rememberMe).catch(() => {
            haveError = true;
        });
    }
</script>

<div class="login-container">
    <div class="card login-card">
        <header class="card-header">
            <p class="card-header-title">Login</p>
        </header>
        <div class="card-content">
            <div class="content">
                <div class="field">
                    <label class="label"
                        >Username
                        <div class="control">
                            <input
                                class="input"
                                class:is-danger={haveError}
                                type="text"
                                bind:value={username}
                            />
                        </div>
                    </label>
                </div>
                <div class="field">
                    <label class="label"
                        >Password
                        <div class="control">
                            <input
                                class="input"
                                class:is-danger={haveError}
                                type="password"
                                bind:value={password}
                            />
                            <p class="help is-danger" class:is-hidden={!haveError}>Invalid username or password.</p>
                        </div>
                    </label>
                </div>
                <div class="field">
                    <div class="control">
                      <label class="checkbox">
                        <input type="checkbox" bind:checked={rememberMe}>
                        Remember me
                      </label>
                    </div>
                  </div>
                <div class="control">
                    <button class="button is-primary" on:click={onLogin}
                        >Login</button
                    >
                </div>
            </div>
        </div>
    </div>
</div>

<style scoped>
    .login-container {
        min-height: 100vh;
        min-width: 100vw;
        display: flex;
        justify-content: center;
        align-items: center;
    }
    .login-card {
        width: 30rem;
    }
</style>

// front/src/layout/Login.vue
<template>
  <div class="login-container color-bg-subtle">
    <div class="Box">
      <div class="Box-header">
        <h3 class="Box-title">Login</h3>
      </div>
      <div class="Box-body">
        <div class="form-group" :class="{errored: errorMessage}">
          <div class="form-group-header">
            <label for="username-input">Username</label>
          </div>
          <div class="form-group-body">
            <input class="form-control" type="text" v-model="user.username"/>
          </div>
        </div>
        <div class="form-group" :class="{errored: errorMessage}">
          <div class="form-group-header">
            <label for="username-input">Password</label>
          </div>
          <div class="form-group-body">
            <input class="form-control" type="password" v-model="user.password"/>
          </div>
        </div>
        <div class="flash flash-error" v-if="errorMessage">
          <span class="octicon"><i class="gg-danger"></i></span> {{errorMessage}}
        </div>
        <div class="form-checkbox">
          <label disabled>
            <input type="checkbox" v-model="rememberMe"/>
            Remember me
          </label>
        </div>
      </div>
      <div class="Box-footer text-right">
        <button class="btn btn-primary" type="button" @click="connect">login</button>
      </div>
    </div>
  </div>
</template>

<style scoped>
.login-container {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
}
.login-container .card {
  min-width: 20rem;
}
</style>

<script>
import authService from "../services/auth.js"

export default {
  components: {},
  data: function() {
    return {
      errorMessage: "",
      rememberMe: true,
      user: {
        username: "",
        password: ""
      }
    }
  },
  methods: {
    connect: function() {
      this.errorMessage = "";
      authService.login(this.user.username, this.user.password, this.rememberMe)
      .then((user) => {
        this.$store.commit('connect', user);
      }).catch((error) => {
        this.errorMessage = error.message;
      });
    }
  }
};
</script>
